name: SpawnProtect
main: bramcraft.spawnprotect.SpawnProtect
version: 1.0
api-version: 1.20
commands:
  setpos1:
    description: Set spawn protection zone position 1
    usage: /setpos1
  setpos2:
    description: Set spawn protection zone position 2
    usage: /setpos2
permissions:
  spawnprotect.setpos:
    description: Allows player to set spawn zone positions
    default: op
  spawnprotect.bypass.break:
    description: Allows player to break blocks in the spawn zone
    default: op
